kind: pipeline
name: default
type: docker

steps:

  - name: build server
    image: umputun/baseimage:buildgo-latest
    commands:
      - cd backend/app
      - go build -mod=vendor

  - name: docker_master
    image: plugins/docker
    repo: umputun/remark42
    secrets: [ docker_username, docker_password]
    build_args:
      - DRONE=${DRONE}
      - DRONE_TAG=${DRONE_TAG}
      - DRONE_COMMIT=${DRONE_COMMIT}
      - DRONE_BRANCH=${DRONE_BRANCH}
    tags:
      - ${DRONE_COMMIT_BRANCH/\//-}
    when:
      branch: [master, release/*]
      event: push

  - name: docker_tag
    image: plugins/docker
    repo: umputun/remark42
    secrets: [ docker_username, docker_password ]
    build_args:
      - DRONE=${DRONE}
      - DRONE_TAG=${DRONE_TAG}
      - DRONE_COMMIT=${DRONE_COMMIT}
    tags:
      - ${DRONE_TAG}
      - latest
    when:
      event: tag

  - name: artifacts_tag
    image: plugins/docker
    dockerfile: Dockerfile.artifacts
    build_args:
      - DRONE=${DRONE}
      - DRONE_TAG=${DRONE_TAG}
      - DRONE_COMMIT=${DRONE_COMMIT}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    when:
      event: tag

  - name: docker_branch
    image: plugins/docker
    settings:
      repo: umputun/remark42
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - DRONE=${DRONE}
        - DRONE_COMMIT=${DRONE_COMMIT}
        - DRONE_BRANCH=${DRONE_BRANCH}
      tags:
        - ${DRONE_COMMIT_BRANCH/\//-}
      dry_run: true
    when:
      branch:
        exclude: [master, release/*]
        event: push

  - name: deploy
    image: docker.umputun.com/system/deploy-ci:master
    commands:
      - ssh umputun@master.radio-t.com "cd /srv/remark && git pull"
      - ssh umputun@master.radio-t.com "cd /srv/remark && docker-compose pull && docker-compose up -d"
    when:
      branch: master
      event: push

  - name: notify
    image: drillster/drone-email
    when:
      status: [ changed, failure ]
    settings:
      host: smtp.mailgun.org
      username:
        from_secret: email_username
      password:
        from_secret: email_password
      from: drone@mg.umputun.dev
      recipients: [ sys@umputun.dev ]


volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock