run:
  tests: false
  output:
    format: tab
  skip-dirs:
    - vendor
linters:
  enable:
    - golint
    - gofmt
    - unconvert
    - megacheck
    - structcheck
    - gas
    - gocyclo
    - dupl
    - misspell
    - unparam
    - varcheck
    - deadcode
    - typecheck
    - ineffassign
    - varcheck
issues:
  exclude-use-default: false
